### PR TITLE
Fix QJSValue Segmentation Fault

### PR DESCRIPTION
**Pull request by samkumar**
Not sure if this is right fix, but this should be a good stopgap so people can continue developing. @immesys, you and I should discuss this at some point.

### CODE REVIEW

**Comment by immesys** [comment]
Interesting. What was it that changed it? Why do you think the error was happening?

**Comment by samkumar** [comment]
I think that the QJSValue copy constructor is a bit glitchy. My "fix" was to just dynamically allocate the callback and thereby copy it only once, rather than copying it every time a Res is called or passed by value. I have not seen it segfault after I did this, though we should discuss if there's a better fix.

**Comment by immesys** [comment]
I believe  the switching should be done inside agent connection but you might also want to verify that the callback is happening on the same thread that called the function

**Comment by samkumar** [comment]
If calling QJSValues occur on a different thread, why would that cause problems? I would imagine that the calls always happen on the thread dedicated to the JSEngine.

**Comment by samkumar** [comment]
If there's a threading problem, it might be that the callback is being invoked in the same thread as the caller, rather than in the thread of the JavaScript engine. I'll investigate this.

**Comment by samkumar** [comment]
Actually, I don't think this is the problem. Yesterday I wrote some C++ code that triggered this bug that never called a QJSValue. I wonder if the problem has to do with calling the copy constructor on a thread different from the JavaScript engine? That would mean that the fix is indeed valid.

**Pull request merged**
